################## Do not edit this file directly ##################
# Place all of your personal configurations in ~/.config/qzsh/zshrc/

source "$HOME/.config/qzsh/qzshrc.zsh"

# Any zshrc configurations under the folder ~/.config/qzsh/zshrc/ will override the default qzsh configs.
ZSH_CONFIGS_DIR="$HOME/.config/qzsh/zshrc"
if [ "$(ls -A $ZSH_CONFIGS_DIR)" ]; then
    for file in "$ZSH_CONFIGS_DIR"/* "$ZSH_CONFIGS_DIR"/.*; do
        if [ -f "$file" ]; then
            source "$file"
        fi
    done
fi
# useful omz libs
[[ -f "$CONFIGDIR/lib/key-bindings.zsh" ]] && source "$CONFIGDIR/lib/key-bindings.zsh"
[[ -f "$CONFIGDIR/lib/theme-and-appearance.zsh" ]] && source "$CONFIGDIR/lib/theme-and-appearance.zsh"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPS="--extended"

[ -f "/home/user/.ghcup/env" ] && . "/home/user/.ghcup/env"